language: python

python:
  - 3.4
  - 3.5
  - 3.6

before_install:
  - sudo apt-get install cmake
  - sudo apt-get install libgit2
  - pip install cffi

install:
  - pip --version
  - pip install -r test-requirements.txt
  - pip install pep8 

before_script:
  - pep8 -v *.py lib/

script:
  - pytest
